### ISSUE TITLE
Problems to Login

### ISSUE THREAD

**Issue by DavidGG2001** [dallmann-consulting/OCPP.Core#64]
Hi,
I've build the program and when I'm about to login  I can't.
![image](https://github.com/user-attachments/assets/e4500b18-0be0-4dac-b32d-3fcc8c238d68)
Anyone knows what the problem can be?

Thanks

**Comment by mstrini** [comment]
And you have used the default-credentials from https://github.com/dallmann-consulting/OCPP.Core/blob/main/OCPP.Core.Management/appsettings.json ? That has worked for me last time...

**Comment by DavidGG2001** [comment]
> And you have used the default-credentials from https://github.com/dallmann-consulting/OCPP.Core/blob/main/OCPP.Core.Management/appsettings.json ? That has worked for me last time...






Yes I prove it but doesn't work. Could it be that I created my OCPP.Core database wrong?

**Comment by DavidGG2001** [comment]
![image](https://github.com/user-attachments/assets/819027e3-9cb0-405c-9ac2-2f6246d8e631)

The error is that can't connect correctly with the database

**Comment by JeremyMahieu** [comment]
You are using a empty connection string, make sure you didn't comment it out in the appsettings.

**Comment by DavidGG2001** [comment]
I tried with the SQLite and the SQLServer and the 2 options are not working

**Comment by dallmann-consulting** [comment]
Please try to configure SQLite and send us the logs here.

**Comment by DavidGG2001** [comment]
I tried with SQLite and now I have this problem
![image](https://github.com/user-attachments/assets/346d33c8-7716-40f8-9ad0-30aeb72c0c34)
 The logs of the manager are this:
: Microsoft.AspNetCore.Server.Kestrel[0] @ 2024-07-18T09:37:42.1837320+02:00
      Overriding address(es) 'http://192.168.2.213:8082'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: OCPP.Core.Management.Controllers.AccountController[0] @ 2024-07-18T09:38:09.3823888+02:00
      User 'admin' logged in
trce: OCPP.Core.Management.Controllers.HomeController[0] @ 2024-07-18T09:38:09.4060899+02:00
      Index: Loading charge points with latest transactions...
fail: OCPP.Core.Management.Controllers.HomeController[0] @ 2024-07-18T09:38:11.5567311+02:00
      Index: Error in status web request => No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión. (192.168.2.213:8081)
System.Net.Http.HttpRequestException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión. (192.168.2.213:8081)
 ---> System.Net.Sockets.SocketException (10061): No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OCPP.Core.Management.Controllers.HomeController.Index() in C:\Users\Proacit\Desktop\OCPP.Core-main\OCPP.Core.Management\Controllers\HomeController.Index.cs:line 91
fail: Microsoft.EntityFrameworkCore.Database.Command[Microsoft.EntityFrameworkCore.Database.Command.CommandError] @ 2024-07-18T09:38:12.4897093+02:00
      Failed executing DbCommand (16ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "c"."ChargePointId", "c"."ConnectorId", "c"."ConnectorName", "c"."LastStatus", "c"."LastStatusTime", "c"."LastMeter", "c"."LastMeterTime", "t"."TransactionId", "t"."StartTagId", "t"."StartTime", "t"."MeterStart", "t"."StartResult", "t"."StopTagId", "t"."StopTime", "t"."MeterStop", "t"."StopReason"
      FROM "ConnectorStatus" AS "c"
      LEFT JOIN "Transactions" AS "t" ON "c"."ChargePointId" = "t"."ChargePointId" AND "c"."ConnectorId" = "t"."ConnectorId"
      WHERE "t"."TransactionId" IS NULL OR "t"."TransactionId" = (
          SELECT MAX("t0"."TransactionId")
          FROM "Transactions" AS "t0"
          WHERE "t0"."ChargePointId" = "c"."ChargePointId" AND "t0"."ConnectorId" = "c"."ConnectorId")
fail: Microsoft.EntityFrameworkCore.Query[Microsoft.EntityFrameworkCore.Query.QueryIterationFailed] @ 2024-07-18T09:38:12.5051967+02:00
      An exception occurred while iterating over the results of a query for context type 'OCPP.Core.Database.OCPPCoreContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: ConnectorStatus'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
         at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: ConnectorStatus'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
fail: OCPP.Core.Management.Controllers.HomeController[0] @ 2024-07-18T09:38:12.5098648+02:00
      Index: Error loading charge points from database
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: ConnectorStatus'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OCPP.Core.Management.Controllers.HomeController.Index() in C:\Users\Proacit\Desktop\OCPP.Core-main\OCPP.Core.Management\Controllers\HomeController.Index.cs:line 140

**Comment by dallmann-consulting** [comment]
Are you sure that you are using the provided sqlite-file? This file contains the missing table:

![image](https://github.com/user-attachments/assets/e15a5d3e-0e7e-4d21-bbcf-90d60eb0faac)

I would suggest you delete the current sqlite-file and download it again from this repoitory.

**Comment by DavidGG2001** [comment]
I think that I finally found the problem
![image](https://github.com/user-attachments/assets/45a6e890-9159-4b88-901a-008357b25d19)
To solve it I have only to put local host in root certificates or something else?
Thanks

**Comment by JeremyMahieu** [comment]
You can put `;TrustServerCertificate=True` in the connection string. Not sure why the repo has =false, but this is a very common one. If it's false you don't need to mention it. Most people just set it to be True if it's a local server, no need to go over the top with certificates if it's localhost anyway.

**Comment by DavidGG2001** [comment]
I tried once more and it worked without any changes. 
Thanks

**Comment by DavidGG2001** [comment]
Very grateful for you help :)
