### ISSUE TITLE
cant run on server

### ISSUE THREAD

**Issue by SayedaliSayedb** [dallmann-consulting/OCPP.Core#75]
Hello  Dear
I cant Run on Server
Is it possible to check where the problem is?

![error2](https://github.com/user-attachments/assets/c8264b8a-8b48-4191-994d-68fe80311069)

![error1](https://github.com/user-attachments/assets/94fa1428-0828-41fe-8885-4b9b5059fe16)

**Comment by SayedaliSayedb** [comment]
I downloaded the [release](https://github.com/dallmann-consulting/OCPP.Core/releases). file and only changed the localhost settings

**Comment by dallmann-consulting** [comment]
Please check if the necessary runtime (like IIS Hosting bundle?) is installed.

**Comment by SayedaliSayedb** [comment]
it I was installed
Can you help me what's rong
Spell uid and pwd or other is rong ?

**Comment by JeremyMahieu** [comment]
Start it in cmd first and show us the output.
```
cd your/install/directory/OCPP.Core.Server
dotnet OCPP.Core.Server.dll
```

**Comment by SayedaliSayedb** [comment]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (31ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
info: Microsoft.EntityFrameworkCore.Migrations[20405]
      No migrations were applied. The database is already up to date.
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: The non-HTTPS endpoint HttpsInlineCertFile includes HTTPS-only configuration for Certificate.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConfigurationReader.ThrowIfContainsHttpsOnlyConfiguration(EndpointConfig endpoint)
         at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
         at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadInternal()
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.InvalidOperationException: The non-HTTPS endpoint HttpsInlineCertFile includes HTTPS-only configuration for Certificate.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConfigurationReader.ThrowIfContainsHttpsOnlyConfiguration(EndpointConfig endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadInternal()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at OCPP.Core.Server.Program.Main(String[] args) in C:\Users\ulrichd\source\repos\GitHub\OCPP.Core\OCPP.Core.Server\Program.cs:line 42

**Comment by dallmann-consulting** [comment]
There is a problem with the SSL hosting. Try to remove the https endpoint from the appsettings:

![image](https://github.com/user-attachments/assets/bff5078a-6900-42f2-a38a-9f12adf5df58)

And then open the browser with a normal "http" url (without "s").

For more details you can google the error message:
_Hosting failed to start System.InvalidOperationException: The non-HTTPS endpoint HttpsInlineCertFile includes HTTPS-only configuration for Certificate._

**Comment by JeremyMahieu** [comment]
![image](https://github.com/user-attachments/assets/60e966e2-9720-4e4c-9c3d-e8f7f0f75294)
This should be https.
